name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x
      - name: Build
        run: dotnet build SST.WebUI
      - name: Test SST.Application.Tests
        run: dotnet test SST.Application.Tests --no-restore
      - name: Test SST.WebUI.tests
        run: dotnet test SST.WebUI.tests --no-restore
